### ISSUE TITLE
having some issues

### ISSUE THREAD

**Issue by ishokuP** [lanlhtomosia97/Itmtu_download#1]
to put it simply i've tried to download ruby along with rvm
`C:/Ruby26-x64/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in 'require': cannot load such file -- pry (LoadError)
        from C:/Ruby26-x64/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in 'require'
        from seifuku_crawl.rb:5:in `<main>'
`
is the error i receive, can you help please?
i may be an idiot at this
![yes](https://user-images.githubusercontent.com/22414146/70239542-726d5800-17a6-11ea-83d9-d5d26c24bf82.png)

**Comment by lanlhtomosia97** [comment]
```
require 'nokogiri'
require 'open-uri'
require 'csv'
require 'thread'
require 'pry'
```
So you must have all that gem. Simple install:
```
gem install nokogiri
gem install open-uri
gem install csv
gem install thread
gem install pry
```
Try again after install all gem.

**Comment by ishokuP** [comment]
will do thanks :D
