### ISSUE TITLE
download does not work

### ISSUE THREAD

**Issue by SKDS** [lanlhtomosia97/Itmtu_download#2]
at the moment he writes 404 to any number that I indicate

**Comment by SKDS** [comment]
screen
https://sun9-38.userapi.com/c855732/v855732505/1f229a/JEd2JcC5_VY.jpg

**Comment by lanlhtomosia97** [comment]
Read README.md again.
```

"=== Insert number ==="

Input the number, ex:

http://www.itmtu.com/mm/69315/
==> 69315
http://www.itmtu.com/mm/68680/
==> 68680
" 
"=== INSERT LAST PAGE ==="

Insert last page you want to download
```
After insert the number of album http://www.itmtu.com/mm/69315/ => 69315
Insert number_page you wanna get it http://www.itmtu.com/mm/69315/40 => 40, not 96316
